// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuBiInNPXWFKW5cFI3_Qe366e8kHJDmI',
    appId: '1:50695825499:web:bd4584e875f28eeb7f377e',
    messagingSenderId: '50695825499',
    projectId: 'spacedog-414600',
    authDomain: 'spacedog-414600.firebaseapp.com',
    storageBucket: 'spacedog-414600.appspot.com',
    measurementId: 'G-RRN0LWD6K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcgDCWX2d1EbbpYf0FQWo3QwVPGllNAY',
    appId: '1:50695825499:android:6639cc0619b3e74a7f377e',
    messagingSenderId: '50695825499',
    projectId: 'spacedog-414600',
    storageBucket: 'spacedog-414600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tnKLzFZL2gRhSLAkdcpd-E_77Uhv6os',
    appId: '1:50695825499:ios:ed5bf24f3564f4797f377e',
    messagingSenderId: '50695825499',
    projectId: 'spacedog-414600',
    storageBucket: 'spacedog-414600.appspot.com',
    iosBundleId: 'com.example.spaceDog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5tnKLzFZL2gRhSLAkdcpd-E_77Uhv6os',
    appId: '1:50695825499:ios:695c397f5a4df1367f377e',
    messagingSenderId: '50695825499',
    projectId: 'spacedog-414600',
    storageBucket: 'spacedog-414600.appspot.com',
    iosBundleId: 'com.example.spaceDog.RunnerTests',
  );
}
